New plugin - fullscreen button
seleb/bipsi-hacks pull request #21
Opened 2023-08-07 02:45 UTC by jon-heard

2023-08-07 14:49 UTC, seleb requested changes
couple minor issues

2023-08-07 14:49 UTC, seleb commented on src/fullscreen button.js
> +fullscreenButton.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" stroke="currentColor" stroke-linecap="round" fill="none" stroke-width="1.25" width="14" height="14"><path d="
imo the icon + style here should be configurable, and the way you've styled this leaves most of the default styling intact, which will make it appear differently on different browsers. i'd recommend injecting a stylesheet and including more deliberate styles (including hover/focus state)

2023-08-07 14:49 UTC, seleb commented on src/fullscreen button.js
> +const fullscreenButton = document.createElement('button');
should add a `title` to this button: atm it has no accessible label

2023-08-07 14:49 UTC, seleb commented on src/fullscreen button.js
> +@version 4.7.0
```suggestion
```

2023-08-08 04:30 UTC, jon-heard commented
I've made all suggested modifications.  I BELIEVE I've overridden all platform-specific button styling: size, padding, margin, color, border.

I tried really hard to show the button while in fullscreen mode.  It requires fullscreening the parent div of the canvas, instead of the canvas itself.  Unfortunately, the canvas parent has a transform style and when it's fullscreened that transform style is invalidated which messes with the fullscreen button size in a way that would be complex to fix.

2023-08-08 14:32 UTC, seleb commented
> I tried really hard to show the button while in fullscreen mode. It requires fullscreening the parent div of the canvas, instead of the canvas itself. Unfortunately, the canvas parent has a transform style and when it's fullscreened that transform style is invalidated which messes with the fullscreen button size in a way that would be complex to fix.

imo it's better to not show the button in fullscreen mode for this case; the browser has native "exit fullscreen" UI that will be shown anyway so the user can't get stuck, and it's unlikely they'd want to toggle states unless they're done playing

2023-08-08 14:32 UTC, seleb approved these changes

2023-08-08 14:33 UTC, merged

2023-08-08 14:36 UTC, seleb commented
:tada: This PR is included in version 4.9.0 :tada:

The release is available on [GitHub release](https://github.com/seleb/bipsi-hacks/releases/tag/v4.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: